# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM ghcr.io/astral-sh/uv:alpine

# Set working directory
WORKDIR /app

# Copy project files
COPY pyproject.toml uv.lock README.md ./
COPY src ./src

# Sync dependencies
RUN uv sync

# Default command to run the MCP server
CMD ["uv", "run", "src/mcp_kakao_local"]
